name: "Build and Deploy docs"
on:
  push:
    branches:
      - master
    paths:
      - packages/jinajs/**
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: yarn install
      - run: yarn jinajs generate-docs
        env:
          CI: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./packages/jinajs/docs

